#!/usr/bin/env sh
# Generates the Homebrew formula (Formula/pg_lens.rb) for dog-hero/homebrew-tap
# from the release tarball checksums. Prints the formula to stdout.
#
# Used by .github/workflows/release.yml (job: update-tap) and runnable by hand:
#
#   scripts/gen_formula.sh 0.2.0 \
#     <sha256 macOS arm64> <sha256 macOS x86_64> \
#     <sha256 Linux arm64 musl> <sha256 Linux x86_64 musl> > Formula/pg_lens.rb
#
# The sha256s are the first column of the .sha256 assets the release publishes.
set -eu

if [ "$#" -ne 5 ]; then
    echo "usage: $0 <version> <sha256-macos-arm64> <sha256-macos-x86_64> <sha256-linux-arm64> <sha256-linux-x86_64>" >&2
    echo "   ex: $0 0.2.0 aaaa... bbbb... cccc... dddd..." >&2
    exit 1
fi

VERSION="${1#v}" # accept both 0.2.0 and v0.2.0
SHA_MAC_ARM="$2"
SHA_MAC_X86="$3"
SHA_LINUX_ARM="$4"
SHA_LINUX_X86="$5"

for sha in "$SHA_MAC_ARM" "$SHA_MAC_X86" "$SHA_LINUX_ARM" "$SHA_LINUX_X86"; do
    case "$sha" in
    *[!0-9a-f]*)
        echo "error: '$sha' is not lowercase hex" >&2
        exit 1
        ;;
    esac
    [ "${#sha}" -eq 64 ] || { echo "error: '$sha' is not 64 chars" >&2; exit 1; }
done

BASE="https://github.com/dog-hero/pg_lens/releases/download/v${VERSION}"

cat <<EOF
# Generated by pg_lens's release workflow (scripts/gen_formula.sh) — do not edit by hand.
class PgLens < Formula
  desc "Live PostgreSQL observability: TUI and web dashboard in one binary"
  homepage "https://github.com/dog-hero/pg_lens"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "${BASE}/pg_lens-v${VERSION}-aarch64-apple-darwin.tar.gz"
      sha256 "${SHA_MAC_ARM}"
    else
      url "${BASE}/pg_lens-v${VERSION}-x86_64-apple-darwin.tar.gz"
      sha256 "${SHA_MAC_X86}"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "${BASE}/pg_lens-v${VERSION}-aarch64-unknown-linux-musl.tar.gz"
      sha256 "${SHA_LINUX_ARM}"
    else
      url "${BASE}/pg_lens-v${VERSION}-x86_64-unknown-linux-musl.tar.gz"
      sha256 "${SHA_LINUX_X86}"
    end
  end

  def install
    bin.install "pg_lens"
  end

  test do
    assert_match "pg_lens", shell_output("#{bin}/pg_lens --help")
  end
end
EOF
