#!/bin/sh
# Generates the Homebrew CASK for pg_lens (macOS prebuilt binaries).
#
# Casks skip Homebrew's development-tools preflight entirely, so users on a
# fresh macOS with an outdated Xcode/CLT can install without errors — the
# formula (kept for Linuxbrew) goes through the source-build path and
# hard-errors on outdated Xcode even though it only ships a binary.
#
# Usage: gen_cask.sh <version> <sha256-mac-arm64> <sha256-mac-x86_64>
#   version may be given with or without the leading "v".
# Output: cask on stdout. Manual publish (assets must be public):
#   V=0.2.1; sha() { curl -sL "https://github.com/dog-hero/pg_lens/releases/download/v$V/pg_lens-v$V-$1.tar.gz.sha256" | cut -d' ' -f1; }
#   scripts/gen_cask.sh $V "$(sha aarch64-apple-darwin)" "$(sha x86_64-apple-darwin)" > Casks/pg_lens.rb
set -eu

[ $# -eq 3 ] || { echo "usage: $0 <version> <sha-mac-arm64> <sha-mac-x86_64>" >&2; exit 1; }
VERSION=${1#v}
SHA_ARM=$2
SHA_X86=$3

for sha in "$SHA_ARM" "$SHA_X86"; do
  case "$sha" in
    *[!0-9a-f]*|"") echo "error: invalid sha256: $sha" >&2; exit 1 ;;
  esac
  [ ${#sha} -eq 64 ] || { echo "error: sha256 must be 64 hex chars: $sha" >&2; exit 1; }
done

cat <<EOF
# Generated by pg_lens's release workflow (scripts/gen_cask.sh) — do not edit by hand.
cask "pg_lens" do
  version "$VERSION"

  arch arm: "aarch64", intel: "x86_64"

  sha256 arm:   "$SHA_ARM",
         intel: "$SHA_X86"

  url "https://github.com/dog-hero/pg_lens/releases/download/v#{version}/pg_lens-v#{version}-#{arch}-apple-darwin.tar.gz"
  name "pg_lens"
  desc "Live PostgreSQL observability: TUI and web dashboard in one binary"
  homepage "https://github.com/dog-hero/pg_lens"

  binary "pg_lens-v#{version}-#{arch}-apple-darwin/pg_lens"
end
EOF
