import { defineConfig } from "vite";

// Two build shapes out of one config:
//
//   `vite build`              → the PRODUCTION bundle. Served by the Rust
//                               binary (rust-embed) at the site root, so the
//                               default absolute `/assets/...` URLs are
//                               correct. Nothing about this shape may change.
//   `vite build --mode demo`  → the GitHub Pages demo (`npm run build:demo`).
//                               Different entry (`demo.html`, generated by
//                               scripts/gen-demo-html.mjs from index.html),
//                               different outDir (`dist-demo/`) and a
//                               `/pg_lens/demo/` base so assets resolve under
//                               the Pages path prefix. It never touches
//                               `dist/`, and no demo code is reachable from
//                               the production entry.
//
// During `vite dev`, API calls are proxied to a locally running `pg_lens serve`.
export default defineConfig(({ mode }) => {
  const demo = mode === "demo";
  return {
    ...(demo ? { base: "/pg_lens/demo/" } : {}),
    server: {
      proxy: {
        "/api": "http://127.0.0.1:8080",
      },
    },
    build: {
      // Keep the embedded payload small and auditable: no sourcemaps in the
      // binary; hashed filenames give far-future caching for free.
      sourcemap: false,
      ...(demo
        ? {
            outDir: "dist-demo",
            emptyOutDir: true,
            rollupOptions: { input: "demo.html" },
          }
        : {}),
    },
  };
});
